Wip admin files
GoSkip/admin-portal pull request #23
Opened 2023-06-07 13:33 UTC by hamdi-standard-ai

- Connected endpoint to fetch files in page `/admin/files`
- Updated UI for page `/admin/files` to match Figma
- WIP: Page `/admin/files/new` to create a new file
- Created reusable components for `dropdown`, `select-list`, and `heading-md`
- Updated reusable components `primary-btn`, `seconday-btn`
- Updated globally the primary color, to use `tailwind` color name instead of `hex-color`.
- Installed and used additional plugin for tailwind `@tailwindcss/forms`
- Caught a `bug` in fetching files API endpoint that blocks adding pagination there and reported to Jira -> https://standardai.atlassian.net/browse/SW-12089

2023-06-07 13:57 UTC, loria33 requested changes

2023-06-07 13:57 UTC, loria33 commented on src/api/file.ts
> +    // limit,
Let's remove unused code

2023-06-07 13:57 UTC, loria33 commented on src/components/dropdown.tsx
> +              const handleItemClick = () => {
Can you move this function so it's not inclined. This will create the function from scratch on every render

2023-06-07 13:57 UTC, loria33 commented on src/routes/admin/files/new/index.tsx
> +      title: "Products (CSV)",
Let's move texts to constants file. So we can change them without code changes

2023-06-07 13:57 UTC, loria33 commented on src/routes/index.tsx
> +import FileNew from "./admin/files/new";
Please remove the below console.log i

2023-06-08 12:40 UTC, hamdi-standard-ai commented on src/components/dropdown.tsx
> +              const handleItemClick = () => {
Solved

2023-06-08 12:41 UTC, hamdi-standard-ai commented on src/routes/admin/files/new/index.tsx
> +      title: "Products (CSV)",
Solved

2023-06-08 12:42 UTC, hamdi-standard-ai commented on src/routes/admin/files/new/index.tsx
> +            Please select a file type to proceed
@loria33 All texts are hard-coded in the project. We don't use eg: `i18n`.
Would you like to start using `i18n`?

2023-06-12 14:47 UTC, merged